-- ============================================================
-- NutriAI :: exercise library seed (bodyweight-first so the
-- calisthenics fallback always has something to prescribe)
-- ============================================================
insert into exercises (slug,name,kind,primary_muscle,secondary_muscles,equipment,difficulty,cues,regression_slug,progression_slug,met) values
('push-up','Push-Up','calisthenics','chest','{triceps,front_delt,core}','{none}',2,'{"Ribs down, glutes tight","Elbows ~45 degrees from torso","Full lockout at top"}','incline-push-up','archer-push-up',8.0),
('incline-push-up','Incline Push-Up','calisthenics','chest','{triceps,front_delt}','{none,bench}',1,'{"Higher surface = easier","Body in one line"}','wall-push-up','push-up',6.0),
('wall-push-up','Wall Push-Up','calisthenics','chest','{triceps}','{none}',1,'{"Stand arm''s length from wall"}',null,'incline-push-up',3.5),
('archer-push-up','Archer Push-Up','calisthenics','chest','{triceps,core}','{none}',4,'{"Shift weight over working arm"}','push-up','one-arm-push-up',9.0),
('one-arm-push-up','One-Arm Push-Up','calisthenics','chest','{core,triceps}','{none}',5,'{"Widen feet for stability"}','archer-push-up',null,10.0),
('bodyweight-squat','Bodyweight Squat','calisthenics','quads','{glutes,core}','{none}',1,'{"Knees track over toes","Chest proud"}','box-squat','bulgarian-split-squat',5.0),
('box-squat','Box Squat','calisthenics','quads','{glutes}','{none,box,bench}',1,'{"Sit back, tap, stand"}',null,'bodyweight-squat',4.5),
('bulgarian-split-squat','Bulgarian Split Squat','strength','quads','{glutes,adductors}','{none,bench,dumbbell}',3,'{"Rear foot elevated","Front shin near vertical"}','reverse-lunge','pistol-squat',6.0),
('pistol-squat','Pistol Squat','calisthenics','quads','{glutes,core}','{none}',5,'{"Counterbalance with arms"}','bulgarian-split-squat',null,8.0),
('reverse-lunge','Reverse Lunge','calisthenics','quads','{glutes,hamstrings}','{none,dumbbell}',2,'{"Step back, drop straight down"}','box-squat','bulgarian-split-squat',6.0),
('goblet-squat','Goblet Squat','strength','quads','{glutes,core}','{dumbbell,kettlebell}',2,'{"Elbows inside knees at bottom"}','bodyweight-squat','front-squat',6.0),
('front-squat','Front Squat','strength','quads','{glutes,core}','{barbell,squat_rack}',4,'{"Elbows high","Brace before descent"}','goblet-squat','back-squat',7.0),
('back-squat','Back Squat','strength','quads','{glutes,hamstrings,core}','{barbell,squat_rack}',4,'{"Bar on upper traps","Break at hips and knees together"}','front-squat',null,7.5),
('deadlift','Conventional Deadlift','strength','hamstrings','{glutes,back,grip}','{barbell,plate}',4,'{"Bar over mid-foot","Lats engaged, push floor away"}','romanian-deadlift',null,7.5),
('romanian-deadlift','Romanian Deadlift','strength','hamstrings','{glutes,back}','{barbell,dumbbell,kettlebell}',3,'{"Hinge, soft knees","Bar stays close"}','hip-hinge','deadlift',6.0),
('hip-hinge','Bodyweight Hip Hinge','calisthenics','hamstrings','{glutes}','{none}',1,'{"Push hips back to a wall"}',null,'romanian-deadlift',3.5),
('kettlebell-swing','Kettlebell Swing','hiit','glutes','{hamstrings,core,shoulders}','{kettlebell}',3,'{"Hips snap, arms are ropes","Float, do not lift"}','romanian-deadlift','kettlebell-snatch',9.8),
('kettlebell-snatch','Kettlebell Snatch','hiit','glutes','{shoulders,core}','{kettlebell}',5,'{"Punch through at the top"}','kettlebell-swing',null,12.0),
('pull-up','Pull-Up','calisthenics','lats','{biceps,core}','{pull_up_bar}',4,'{"Chest to bar","Full hang at bottom"}','band-assisted-pull-up','weighted-pull-up',8.0),
('band-assisted-pull-up','Band-Assisted Pull-Up','calisthenics','lats','{biceps}','{pull_up_bar,resistance_band}',2,'{"Band under knee or foot"}','inverted-row','pull-up',6.0),
('weighted-pull-up','Weighted Pull-Up','strength','lats','{biceps,core}','{pull_up_bar,plate}',5,'{"Control the descent"}','pull-up',null,9.0),
('inverted-row','Inverted Row','calisthenics','back','{biceps,rear_delt}','{none,barbell,trx,squat_rack}',2,'{"Body rigid, pull chest to bar"}',null,'pull-up',5.5),
('bent-over-row','Bent-Over Row','strength','back','{biceps,rear_delt}','{barbell,dumbbell}',3,'{"Hinge to ~45 degrees","Drive elbows back"}','inverted-row',null,6.0),
('dumbbell-row','Single-Arm Dumbbell Row','strength','back','{biceps,core}','{dumbbell,bench}',2,'{"No torso rotation"}','inverted-row','bent-over-row',5.5),
('bench-press','Barbell Bench Press','strength','chest','{triceps,front_delt}','{barbell,bench,squat_rack}',3,'{"Shoulder blades pinched","Bar to lower chest"}','dumbbell-press','weighted-dip',6.0),
('dumbbell-press','Dumbbell Bench Press','strength','chest','{triceps,front_delt}','{dumbbell,bench}',2,'{"Wrists stacked over elbows"}','push-up','bench-press',5.5),
('overhead-press','Overhead Press','strength','shoulders','{triceps,core}','{barbell,dumbbell}',3,'{"Squeeze glutes, no lean back"}','pike-push-up',null,6.0),
('pike-push-up','Pike Push-Up','calisthenics','shoulders','{triceps}','{none}',3,'{"Hips high, crown to floor"}','incline-push-up','handstand-push-up',7.0),
('handstand-push-up','Handstand Push-Up','calisthenics','shoulders','{triceps,core}','{none}',5,'{"Wall for balance"}','pike-push-up',null,9.0),
('weighted-dip','Weighted Dip','strength','chest','{triceps}','{pull_up_bar,plate}',4,'{"Slight forward lean"}','dip',null,8.0),
('dip','Parallel Bar Dip','calisthenics','triceps','{chest,front_delt}','{pull_up_bar,none}',3,'{"Shoulders stay above elbows"}','bench-dip','weighted-dip',7.0),
('bench-dip','Bench Dip','calisthenics','triceps','{front_delt}','{bench,none}',1,'{"Keep hips close to bench"}',null,'dip',4.5),
('plank','Plank','core','core','{shoulders,glutes}','{none}',1,'{"Posterior tilt, breathe"}',null,'rollout',3.0),
('hollow-hold','Hollow Body Hold','core','core','{hip_flexors}','{none}',3,'{"Low back glued to floor"}','plank','rollout',4.0),
('rollout','Ab Wheel / Barbell Rollout','core','core','{lats}','{barbell,medicine_ball}',4,'{"No hip sag"}','plank',null,5.0),
('hanging-leg-raise','Hanging Leg Raise','core','core','{hip_flexors,grip}','{pull_up_bar}',4,'{"Posterior tilt at the top"}','hollow-hold',null,5.0),
('band-pull-apart','Band Pull-Apart','mobility','rear_delt','{traps}','{resistance_band}',1,'{"Straight arms, squeeze"}',null,null,3.0),
('face-pull','Face Pull','strength','rear_delt','{traps,rotator_cuff}','{cable_machine,resistance_band}',2,'{"Pull to forehead, thumbs back"}','band-pull-apart',null,4.0),
('burpee','Burpee','hiit','full_body','{quads,chest,core}','{none}',3,'{"Chest to floor, jump at top"}','squat-thrust',null,10.0),
('squat-thrust','Squat Thrust','hiit','full_body','{quads,core}','{none}',2,'{"Step back instead of jumping"}',null,'burpee',7.0),
('mountain-climber','Mountain Climber','hiit','core','{quads,shoulders}','{none}',2,'{"Hips low, quick feet"}',null,'burpee',8.0),
('jump-rope','Jump Rope','cardio','calves','{core,shoulders}','{jump_rope,none}',2,'{"Small hops, wrists turn the rope"}',null,null,11.0),
('rowing','Rowing Machine','cardio','back','{legs,core}','{rower}',2,'{"Legs, hips, arms - then reverse"}',null,null,8.5),
('treadmill-run','Treadmill Run','cardio','legs','{core}','{treadmill}',2,'{"Relaxed shoulders, cadence ~175"}',null,null,9.8),
('stationary-bike','Stationary Bike','cardio','quads','{glutes,calves}','{bike}',1,'{"Saddle height: slight knee bend"}',null,null,7.0),
('walking','Brisk Walk','cardio','legs','{core}','{none}',1,'{"Conversational pace"}',null,'treadmill-run',3.8),
('cat-cow','Cat-Cow','mobility','spine','{core}','{none}',1,'{"Move with the breath"}',null,null,2.3),
('worlds-greatest-stretch','World''s Greatest Stretch','mobility','hips','{thoracic,hamstrings}','{none}',2,'{"Elbow to instep, then rotate"}',null,null,3.0)
on conflict (slug) do nothing;
