-- ============================================================
-- NeutriAI :: 0020  normalise the vessel label on saved calibrations
--
-- `scan_calibrations.vessel` is typed by a person ("Bowl", "soup bowl",
-- "bowl ") and matched at scan time against a value generated by the vision
-- model ("bowl"). Raw string equality therefore failed for most real rows, the
-- calibration was skipped, and the photo fell back to the user's default
-- calibration -- usually a dinner plate. On a bowl that is roughly the 2x
-- error migration 0015 was written about, and nothing told the user their
-- measurement had not been used.
--
-- Both sides now normalise the same way: trim, lowercase, spaces and hyphens
-- to underscores. This brings existing rows into line with that.
-- ============================================================

update scan_calibrations
set vessel = replace(replace(lower(btrim(vessel)), ' ', '_'), '-', '_')
where vessel is not null
  and vessel <> replace(replace(lower(btrim(vessel)), ' ', '_'), '-', '_');
